# Generated by Django 3.1.7 on 2021-03-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210315_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('gray', 'Gray'), ('blue', 'Blue'), ('purple', 'Purple')], default='gray', max_length=200),
        ),
    ]
